### ISSUE TITLE
where can I download imagenet_full_size-061417.tar.gz

### ISSUE THREAD

**Issue by jonibek95** [facebookresearch/ijepa#18]
Thank you for your great ptoject. I try to run main.py, where to download /imagenet_full_size/061417?
I got this error 
![image](https://github.com/facebookresearch/ijepa/assets/84657258/263fae8d-e520-4b50-9aeb-d5a9d48c5f21)

**Comment by MidoAssran** [comment]
Hi @jonibek95, if you don't already have ImageNet downloaded on your cluster, I believe you can download it from the imag-net.org website!

**Comment by lxrlxrrr** [comment]
@jonibek95  Excuse me, has your problem been solved?
