### ISSUE TITLE
Capitalization correction in README.md

### ISSUE THREAD

**Issue by aroramrinaal** [facebookresearch/ijepa#19]
### Description:
I noticed a minor capitalization inconsistency in the README.md file, specifically in the section describing the benefits of I-JEPA. The word "Without" is currently written in lowercase, and I propose capitalizing it for consistency and clarity.

### Proposed Change:
Capitalize the word "Without" in the following sentence to maintain consistency with the capitalization of other sentences:

### Original Sentence:
"...without relying on pre-specified invariances to hand-crafted data transformations..."

### Proposed Sentence:

1. Without relying on pre-specified invariances to hand-crafted data transformations, which tend to be biased for particular downstream tasks,
2. And without having the model fill in pixel-level details, which tend to result in learning less semantically meaningful representations.

This change will help improve the readability and maintain a consistent writing style throughout the [README.md](https://github.com/facebookresearch/ijepa/blob/main/README.md?plain=1) file.

**Comment by MidoAssran** [comment]
Hi @aroramrinaal, thanks for your suggestion. Not sure that it makes a big difference in terms of clarity, will close this issue for now.
