### ISSUE TITLE
Automatic1111 Integration

### ISSUE THREAD

**Issue by Ashdevz** [facebookresearch/ijepa#23]
Can anybody tell me if this can be integrated in to Automatic1111? 

Thanks

**Comment by MRQJsfhf** [comment]
Want to know if this model can run at least 4090Ti?

**Comment by MidoAssran** [comment]
HI @Ashdevz, happy to help support any integration you want to try!

**Comment by MidoAssran** [comment]
@MRQJsfhf yes I think it should. The main changes would just be to set `use_bfloat16: false` in the config, and to replace `torch.bfloat16` on [line 316 in train.py](https://github.com/facebookresearch/ijepa/blob/main/src/train.py#L316) with `torch.float16`.

(let me know if you try this an encounter any unexpected issues)
