### ISSUE TITLE
minimum ijepa,  100+ lines  (except vit(<100 lines) and mask(can be <100 lines))

### ISSUE THREAD

**Issue by yuedajiong** [facebookresearch/ijepa#26]
**minimum ijepa**

**https://github.com/yuedajiong/minimum-ijepa**

no distribution(for one GPU), no bfloat16(for low-end GPU),  mini dataset from cifar10 or imagenet-mini.

main logic in 1-2 screen(s).

**Comment by MidoAssran** [comment]
Looks awesome @yuedajiong!
