### ISSUE TITLE
Is the VIT predictor important?

### ISSUE THREAD

**Issue by ItakeLs** [facebookresearch/ijepa#29]
Hello, I read your paper and enjoyed it very much. I understand that the predictor is necessary to prevent representational collapse, since it is used to predict missing information based on the information it has. I am not sure if I missed it but does the predictor have to be a VIT, or could the decoder/predictor be any reasonable architecture such as a group of linear layers. Would the decoder not being a ViT prevent the model from learning robust high-level semantic representations?

**Comment by ballasnicolas** [comment]
Hi, thank you for your interest in our work!

In this work, we mostly focused on  a VIT predictor and we did not explore other parametrization. However, I  think the method could work with any architecture (such as convnet or other). However, the predictor needs to be expressive enough to solve the pretraining task. For instance, see table 12 in appendix looking at the impact of the predictor depth, a deeper predictor leads to better downstream performance..  

You can also check data2vec-v2 (https://arxiv.org/abs/2212.07525) another work that explores similar pretraining tasks (predicting missing information in representation space) and uses a convolutional network as their predictor.
