### ISSUE TITLE
Making the code a bit more installable

### ISSUE THREAD

**Issue by lanalex** [facebookresearch/ijepa#33]
Hi,

1. I made some small modifications to make the code more installable  (using namespace and not src so it can be pip installed) and usable with import (like ijepa.utils) in other packages. So for example its easy to load the train model . 
2. Also the ability to run training not in data parallel on osx (or none gpu machine). 

Will it be ok to open a pull request?  

Thanks!

**Comment by MidoAssran** [comment]
Hey @lanalex, happy to take a look at a PR :)
