### ISSUE TITLE
Torch version

### ISSUE THREAD

**Issue by KyeonghaRho** [facebookresearch/ijepa#37]
Hi, thank you for sharing your great work.
I have a question.
According to the Readme file, you recommend the torch 2.0.
I'm using torch 1.12, and are there any probabilities that the torch version might make the problems?

**Comment by MidoAssran** [comment]
Hi @KyeonghaRho, you should be fine with a different torch version, but you may need to make some small changes if you get errors. For example, perhaps `torch.bfloat16` is not defined, in which case you may need to remove this part from the code, or replace it with `torch.float16`, which tends to have stability issues.

In general, we observed non-trivial improvements in training efficiency simply by switching to PyTorch 2.0, so if it's accessible to you I would highly encourage using this newer version.
