### ISSUE TITLE
All blocks have same size within a batch

### ISSUE THREAD

**Issue by aRI0U** [facebookresearch/ijepa#38]
Hi,
I'm currently exploring I-JEPA and I have a question about the multiblock mask collator.
I see that in the collator you sample `p_size` and `e_size` outside of the loop that iterates over the batch, so all blocks from a batch have the same size.

Is it something required for the model to work, or is it just because it was easier to implement? Or is it eventually to avoid padding issues?

Thanks a lot!

**Comment by MidoAssran** [comment]
Hi @aRI0U, this is simply to avoid padding. You need the same number of tokens for each image in the batch to process them efficiently! However, note that the sampled block sizes on different GPUs in **the same iteration** could be different, thus not all images in the global batch are guaranteed to have the same block size.

**Comment by aRI0U** [comment]
Ok I see that's smart, thanks a lot for your prompt reply!
