### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by shxingch** [facebookresearch/ijepa#43]
Fitrstly, thanks for your great work! 
But when I want to run the `in1k_vith14_ep300.yaml` with the guidence, I have met a mistake:

```
File "/ijepa-main/main.py", line 52, in process_main
    app_main(args=params)
File "/ijepa-main/src/train.py", line 221, in main 
    encoder = DistributedDataParallel(encoder, static_graph=True)
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

I have a device with two GPUs, both of which are RTX 3090. How could I solve this problem? If you can provide assistance, I would greatly appreciate it.

**Comment by MartinKlefas** [comment]
There's a [Pull Request](https://github.com/facebookresearch/ijepa/pull/28) for some code that fixed this error for me. If you make the same changes to your source code you can start running.

**Comment by ikoltech** [comment]
Thank you for your assistance! After making changes to `train.py`, I was able to run the code successfully. I greatly appreciate your help.

**Comment by shxingch** [comment]
Thank you for your assistance! After making changes to `train.py`, I was able to run the code successfully. I greatly appreciate your help.
